services:
  - type: web
    name: ink-detection-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install uv && uv sync
    startCommand: bash startup.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0